<?php

namespace App\Consts;

class MenuConsts
{
    // MENUルーティング
    // 第1階層
    public const DEF1_1 = ''; //販売管理
    public const DEF1_2 = ''; //購買管理
    public const DEF1_3 = ''; //在庫管理
    public const DEF1_4 = ''; //マスタ管理
    public const DEF1_5 = ''; //データ連携
    public const DEF1_6 = ''; //システム
    public const DEF1_7 = ''; //特化型分析

    public const DEF1 = [
        1 => self::DEF1_1,
        2 => self::DEF1_2,
        3 => self::DEF1_3,
        4 => self::DEF1_4,
        5 => self::DEF1_5,
        6 => self::DEF1_6,
        7 => self::DEF1_7,
    ];

    // 第2階層
    public const DEF2_1 = ''; //受注
    public const DEF2_2 = ''; //出荷
    public const DEF2_3 = ''; //売上
    public const DEF2_4 = ''; //請求
    public const DEF2_5 = ''; //売掛
    public const DEF2_6 = ''; //発注
    public const DEF2_7 = ''; //仕入
    public const DEF2_8 = ''; //支払
    public const DEF2_9 = ''; //買掛
    public const DEF2_10 = ''; //在庫
    public const DEF2_11 = ''; //棚卸
    public const DEF2_12 = ''; //分析
    public const DEF2_13 = ''; //得意先
    public const DEF2_14 = ''; //納品先
    public const DEF2_15 = ''; //仕入先
    public const DEF2_16 = ''; //商品
    public const DEF2_17 = ''; //単価
    public const DEF2_18 = ''; //その他
    public const DEF2_19 = ''; //EC関連
    public const DEF2_20 = ''; //KEYENCE
    public const DEF2_21 = ''; //日本郵政
    public const DEF2_22 = ''; //セキュリティ
    public const DEF2_23 = ''; //環境設定
    public const DEF2_24 = ''; //明細表
    public const DEF2_25 = ''; //集計表

    public const DEF2 = [
        1 => self::DEF2_1,
        2 => self::DEF2_2,
        3 => self::DEF2_3,
        4 => self::DEF2_4,
        5 => self::DEF2_5,
        6 => self::DEF2_6,
        7 => self::DEF2_7,
        8 => self::DEF2_8,
        9 => self::DEF2_9,
        10 => self::DEF2_10,
        11 => self::DEF2_11,
        12 => self::DEF2_12,
        13 => self::DEF2_13,
        14 => self::DEF2_14,
        15 => self::DEF2_15,
        16 => self::DEF2_16,
        17 => self::DEF2_17,
        18 => self::DEF2_18,
        19 => self::DEF2_19,
        20 => self::DEF2_20,
        21 => self::DEF2_21,
        22 => self::DEF2_22,
        23 => self::DEF2_23,
        24 => self::DEF2_24,
        25 => self::DEF2_25,
    ];

    // 第3階層
    public const DEF3_1 = 'sales_management.order_receive.accountant.index'; //
    public const DEF3_2 = 'sales_management.order_receive.accountant.list'; //
    public const DEF3_3 = 'sales_management.order_receive.accountant.inquiry'; //
    public const DEF3_4 = 'sales_management.order_receive.in_shipping.inquiry'; //
    public const DEF3_5 = 'sales_management.shipping.picking_list.issue.index'; //
    public const DEF3_6 = 'sales_management.shipping.inspection.index'; //
    public const DEF3_7 = 'sales_management.shipping.sale.decision.index'; //
    public const DEF3_8 = 'sales_management.shipping.guidance.issue.index'; //
    public const DEF3_9 = 'sales_management.shipping.total_picking_list.issue.index'; //
    public const DEF3_10 = 'sales_management.sales.accountant.index'; //
    public const DEF3_11 = 'sales_management.sales.slip.issue.index'; //
    public const DEF3_12 = 'sales_management.sales.checklist.index'; //
    public const DEF3_13 = 'sales_management.demand.closing_date.change.index'; //
    public const DEF3_14 = 'sales_management.demand.sequentially.closing.index'; //
    public const DEF3_15 = 'sales_management.demand.sequentially.closing.remove.index'; //
    public const DEF3_16 = 'sales_management.demand.tax.calculate.index'; //
    public const DEF3_17 = 'sales_management.demand.data.decision.index'; //
    public const DEF3_18 = 'sales_management.demand.balance.inquiry.index'; //
    public const DEF3_19 = 'sales_management.demand.history.inquiry.index'; //
    public const DEF3_20 = 'sales_management.demand.invoice.list.index'; //
    public const DEF3_21 = 'sales_management.demand.invoice.issue.index'; //
    public const DEF3_22 = 'sales_management.accounts_receivable.payment.index'; //
    public const DEF3_23 = 'sales_management.accounts_receivable.checklist.index'; //
    public const DEF3_24 = 'sales_management.accounts_receivable.collect_balance.list.index'; //
    public const DEF3_25 = 'sales_management.accounts_receivable.bill_receipt.list.index'; //
    public const DEF3_26 = 'sales_management.accounts_receivable.list.index'; //
    public const DEF3_27 = 'sales_management.accounts_receivable.customer_ledger.index'; //
    public const DEF3_28 = 'sales_management.accounts_receivable.customer_overview.inquiry.index'; //
    public const DEF3_29 = 'purchase_management.order.accountant.index'; //
    public const DEF3_30 = ''; //
    public const DEF3_31 = ''; //
    public const DEF3_32 = ''; //
    public const DEF3_33 = ''; //
    public const DEF3_34 = ''; //
    public const DEF3_35 = ''; //
    public const DEF3_36 = ''; //
    public const DEF3_37 = ''; //
    public const DEF3_38 = ''; //
    public const DEF3_39 = ''; //
    public const DEF3_40 = ''; //
    public const DEF3_41 = ''; //
    public const DEF3_42 = ''; //
    public const DEF3_43 = ''; //
    public const DEF3_44 = ''; //
    public const DEF3_45 = ''; //
    public const DEF3_46 = 'purchase_management.accounts_payable.accountant.index'; //
    public const DEF3_47 = 'purchase_management.accounts_payable.accountant.index'; //
    public const DEF3_48 = 'purchase_management.accounts_payable.accountant.index'; //
    public const DEF3_49 = 'stock_management.stock.in_out.input.index'; //入出庫入力
    public const DEF3_50 = 'stock_management.stock.in_out.checklist.index'; //入出庫チェックリスト
    public const DEF3_51 = 'stock_management.stock.list.index'; //在庫一覧表
    public const DEF3_52 = 'stock_management.stock.warehouse.list.index'; //商品別倉庫別在庫一覧表
    public const DEF3_53 = 'stock_management.stock.data.output.index'; //在庫データ書出し
    public const DEF3_54 = 'stock_management.stock.stock_moving.import.index'; //在庫移動Excel取込
    public const DEF3_55 = 'stock_management.inventory.slip.index'; //棚卸原票
    public const DEF3_56 = 'stock_management.inventory.start.index'; //棚卸開始処理
    public const DEF3_57 = 'stock_management.inventory.accountant.index'; //棚卸計上入力
    public const DEF3_58 = 'stock_management.inventory.checklist.index'; //棚卸チェックリスト
    public const DEF3_59 = 'stock_management.inventory.update.index'; //棚卸更新処理
    public const DEF3_60 = 'stock_management.inventory.end.index'; //棚卸終了処理
    public const DEF3_61 = 'stock_management.inventory.difference.list.index'; //棚卸差異表
    public const DEF3_62 = 'stock_management.inventory.import.index'; //棚卸Excel取込
    public const DEF3_63 = 'stock_management.analysis.asset_stock.list.index'; //分析 -> 資産在庫表
    public const DEF3_64 = 'master.customer.mt_customer_class.index'; //マスタ管理はここから、他は後日
    public const DEF3_65 = 'master.customer.mt_customer.detail'; //
    public const DEF3_66 = 'master.customer.mt_customer_class.list'; //
    public const DEF3_67 = 'master.customer.mt_customer.list'; //
    public const DEF3_68 = 'master.customer.mt_customer.file.index'; //
    public const DEF3_69 = 'master.delivery.mt_delivery_destinations.index'; //
    public const DEF3_70 = 'master.delivery.mt_delivery_destinations.detail.index'; //
    public const DEF3_71 = 'master.delivery.mt_delivery_destinations.list'; //
    public const DEF3_72 = 'master.delivery.mt_delivery_destinations.file.index'; //
    public const DEF3_73 = 'master.supplier.mt_supplier_class.index'; //
    public const DEF3_74 = 'master.supplier.mt_supplier.detail'; //
    public const DEF3_75 = 'master.supplier.mt_supplier_class.list'; //
    public const DEF3_76 = 'master.supplier.mt_supplier.list'; //
    public const DEF3_77 = 'master.item.mt_color.index'; //
    public const DEF3_78 = 'master.item.mt_size.index'; //
    public const DEF3_79 = 'master.item.mt_color_pattern.index'; //
    public const DEF3_80 = 'master.item.mt_size_pattern.index'; //
    public const DEF3_81 = 'master.item.mt_item_class.index'; //
    public const DEF3_82 = 'master.item.mt_item.detail'; //
    public const DEF3_83 = 'master.item.jan.list'; //
    public const DEF3_84 = 'master.item.mt_color.list'; //
    public const DEF3_85 = 'master.item.mt_size.list'; //
    public const DEF3_86 = 'master.item.mt_color_pattern.list'; //
    public const DEF3_87 = 'master.item.mt_size_pattern.list'; //
    public const DEF3_88 = 'master.item.mt_item_class.list'; //
    public const DEF3_89 = 'master.item.mt_item.list'; //
    public const DEF3_90 = 'master.item.mt_item.class.list'; //
    public const DEF3_91 = 'master.item.mt_item.file.index'; //
    public const DEF3_92 = 'master.price.mt_customer_other_item_class_rate.index_for_new'; //
    public const DEF3_93 = 'master.price.mt_customer_other_item_class_rate.list'; //
    public const DEF3_94 = 'master.price.mt_customer_other_item_rate.index_for_new'; //
    public const DEF3_95 = 'master.price.mt_customer_other_item_rate.list'; //
    public const DEF3_96 = 'master.price.mt_customer_other_item_rate.ps_kbn.index'; //
    public const DEF3_97 = 'master.price.selling_price.index'; //
    public const DEF3_98 = 'master.price.selling_price.list'; //
    public const DEF3_99 = 'master.price.mt_supplier_item_price.index'; //
    public const DEF3_100 = 'master.price.mt_supplier_item_price.list'; //
    public const DEF3_101 = 'master.other.mt_bank.index'; //
    public const DEF3_102 = 'master.other.mt_bank.list'; //
    public const DEF3_103 = 'master.other.mt_shipping_company.index'; //
    public const DEF3_104 = 'master.other.mt_shipping_company.list'; //
    public const DEF3_105 = 'master.other.mt_warehouse.index'; //
    public const DEF3_106 = 'master.other.mt_warehouse.list'; //
    public const DEF3_107 = 'master.other.mt_item_change_history.list'; //
    public const DEF3_108 = 'master.other.mt_stock_keeping_unit.list'; //
    public const DEF3_109 = 'master.other.mt_location.index'; //
    public const DEF3_110 = 'master.other.mt_location.list'; //
    public const DEF3_111 = 'master.other.mt_location.file.index'; //
    public const DEF3_112 = 'master.other.mt_root.index'; //
    public const DEF3_113 = 'master.other.mt_item.item_cd.index'; //
    public const DEF3_114 = 'alignment.keyence.sales_data.import.index'; //
    public const DEF3_115 = 'alignment.keyence.in_out_data.import.index'; //
    public const DEF3_116 = 'alignment.jph.item_data.output.index'; //
    public const DEF3_117 = 'alignment.jph.shipping_instruction.output.index'; //
    public const DEF3_118 = 'alignment.jph.shipping_data.import.index'; //
    public const DEF3_119 = 'system.security.user.list'; //
    public const DEF3_120 = 'system.environment.company.index'; //
    public const DEF3_121 = 'system.environment.slip_kind.index'; //
    public const DEF3_122 = 'system.environment.tax_rate.index'; //
    public const DEF3_123 = 'system.environment.sticky_note.index'; //
    public const DEF3_124 = 'system.environment.holiday.index'; //
    public const DEF3_125 = 'analyse.detail.search_recived_order_for_check.analyse'; //
    public const DEF3_126 = 'analyse.detail.daily_payment.analyse'; //
    public const DEF3_127 = 'analyse.detail.monthly_payment.analyse'; //
    public const DEF3_128 = 'analyse.detail.return_after_payment.analyse'; //
    public const DEF3_129 = 'analyse.detail.payment_by_customer.analyse'; //
    public const DEF3_130 = 'analyse.detail.search_recived_order.analyse'; //
    public const DEF3_131 = 'analyse.detail.search_sale.analyse'; //
    public const DEF3_132 = 'analyse.detail.customer_data.analyse'; //
    public const DEF3_133 = 'analyse.detail.customer_delivery_destination_data.analyse'; //
    public const DEF3_134 = 'analyse.detail.check_received_order.analyse'; //
    public const DEF3_135 = 'analyse.detail.check_return.analyse'; //
    public const DEF3_136 = 'analyse.detail.search_large_received_order.analyse'; //
    public const DEF3_137 = 'analyse.detail.backlog_without_location.analyse'; //
    public const DEF3_138 = 'analyse.detail.check_assigned_outstanding_order.analyse'; //
    public const DEF3_139 = 'analyse.detail.outstanding_order_master.analyse'; //
    public const DEF3_140 = 'analyse.tally.gross_profit_chart.analyse'; //
    public const DEF3_141 = ''; //
    public const DEF3_142 = 'analyse.tally.check_shipping_document_number.analyse'; //
    public const DEF3_143 = 'analyse.tally.check_shipping.analyse'; //
    public const DEF3_144 = 'analyse.tally.check_outstanding_order_and_backlog.analyse'; //
    public const DEF3_145 = 'analyse.tally.backlog.analyse'; //
    public const DEF3_146 = 'analyse.tally.outstanding_order.analyse'; //
    public const DEF3_147 = 'master.ec.catalog.detail'; //
    public const DEF3_148 = 'master.ec.top_free_area.detail'; //
    public const DEF3_149 = 'master.ec.notice.detail'; //

    public const DEF3 = [
        1 => self::DEF3_1,
        2 => self::DEF3_2,
        3 => self::DEF3_3,
        4 => self::DEF3_4,
        5 => self::DEF3_5,
        6 => self::DEF3_6,
        7 => self::DEF3_7,
        8 => self::DEF3_8,
        9 => self::DEF3_9,
        10 => self::DEF3_10,
        11 => self::DEF3_11,
        12 => self::DEF3_12,
        13 => self::DEF3_13,
        14 => self::DEF3_14,
        15 => self::DEF3_15,
        16 => self::DEF3_16,
        17 => self::DEF3_17,
        18 => self::DEF3_18,
        19 => self::DEF3_19,
        20 => self::DEF3_20,
        21 => self::DEF3_21,
        22 => self::DEF3_22,
        23 => self::DEF3_23,
        24 => self::DEF3_24,
        25 => self::DEF3_25,
        26 => self::DEF3_26,
        27 => self::DEF3_27,
        28 => self::DEF3_28,
        29 => self::DEF3_29,
        30 => self::DEF3_30,
        31 => self::DEF3_31,
        32 => self::DEF3_32,
        33 => self::DEF3_33,
        34 => self::DEF3_34,
        35 => self::DEF3_35,
        36 => self::DEF3_36,
        37 => self::DEF3_37,
        38 => self::DEF3_38,
        39 => self::DEF3_39,
        40 => self::DEF3_40,
        41 => self::DEF3_41,
        42 => self::DEF3_42,
        43 => self::DEF3_43,
        44 => self::DEF3_44,
        45 => self::DEF3_45,
        46 => self::DEF3_46,
        47 => self::DEF3_47,
        48 => self::DEF3_48,
        49 => self::DEF3_49,
        50 => self::DEF3_50,
        51 => self::DEF3_51,
        52 => self::DEF3_52,
        53 => self::DEF3_53,
        54 => self::DEF3_54,
        55 => self::DEF3_55,
        56 => self::DEF3_56,
        57 => self::DEF3_57,
        58 => self::DEF3_58,
        59 => self::DEF3_59,
        60 => self::DEF3_60,
        61 => self::DEF3_61,
        62 => self::DEF3_62,
        63 => self::DEF3_63,
        64 => self::DEF3_64,
        65 => self::DEF3_65,
        66 => self::DEF3_66,
        67 => self::DEF3_67,
        68 => self::DEF3_68,
        69 => self::DEF3_69,
        70 => self::DEF3_70,
        71 => self::DEF3_71,
        72 => self::DEF3_72,
        73 => self::DEF3_73,
        74 => self::DEF3_74,
        75 => self::DEF3_75,
        76 => self::DEF3_76,
        77 => self::DEF3_77,
        78 => self::DEF3_78,
        79 => self::DEF3_79,
        80 => self::DEF3_80,
        81 => self::DEF3_81,
        82 => self::DEF3_82,
        83 => self::DEF3_83,
        84 => self::DEF3_84,
        85 => self::DEF3_85,
        86 => self::DEF3_86,
        87 => self::DEF3_87,
        88 => self::DEF3_88,
        89 => self::DEF3_89,
        90 => self::DEF3_90,
        91 => self::DEF3_91,
        92 => self::DEF3_92,
        93 => self::DEF3_93,
        94 => self::DEF3_94,
        95 => self::DEF3_95,
        96 => self::DEF3_96,
        97 => self::DEF3_97,
        98 => self::DEF3_98,
        99 => self::DEF3_99,
        100 => self::DEF3_100,
        101 => self::DEF3_101,
        102 => self::DEF3_102,
        103 => self::DEF3_103,
        104 => self::DEF3_104,
        105 => self::DEF3_105,
        106 => self::DEF3_106,
        107 => self::DEF3_107,
        108 => self::DEF3_108,
        109 => self::DEF3_109,
        110 => self::DEF3_110,
        111 => self::DEF3_111,
        112 => self::DEF3_112,
        113 => self::DEF3_113,
        114 => self::DEF3_114,
        115 => self::DEF3_115,
        116 => self::DEF3_116,
        117 => self::DEF3_117,
        118 => self::DEF3_118,
        119 => self::DEF3_119,
        120 => self::DEF3_120,
        121 => self::DEF3_121,
        122 => self::DEF3_122,
        123 => self::DEF3_123,
        124 => self::DEF3_124,
        125 => self::DEF3_125,
        126 => self::DEF3_126,
        127 => self::DEF3_127,
        128 => self::DEF3_128,
        129 => self::DEF3_129,
        130 => self::DEF3_130,
        131 => self::DEF3_131,
        132 => self::DEF3_132,
        133 => self::DEF3_133,
        134 => self::DEF3_134,
        135 => self::DEF3_135,
        136 => self::DEF3_136,
        137 => self::DEF3_137,
        138 => self::DEF3_138,
        139 => self::DEF3_139,
        140 => self::DEF3_140,
        141 => self::DEF3_141,
        142 => self::DEF3_142,
        143 => self::DEF3_143,
        144 => self::DEF3_144,
        145 => self::DEF3_145,
        146 => self::DEF3_146,
        147 => self::DEF3_147,
        148 => self::DEF3_148,
        149 => self::DEF3_149,
    ];
}
